LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_C_INCLUDES += $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include
LOCAL_SRC_FILES:= myexe.c
LOCAL_MODULE:= myexe
LOCAL_MODULE_TAGS := optional

include $(BUILD_EXECUTABLE)
